server {
    listen       80;
    server_name  "";

    location / {
        root  /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;
    }

    location /healthcheck {
        return 200 'OK';
    }

    # После прочтения сжечь!!! Временое решение для проброса к backend локальному серверу. IP поменять на свой, из докера localhost внешний не виден!
    location /asdku/ {
        proxy_pass http://192.168.0.18:8080/asdku/;
    }
}
